// 导出"安全周报/月报"：在新窗口渲染一份打印友好的报告，用户用浏览器"打印 → 存为 PDF"即可。
// 不依赖任何后端/第三方库，跨平台稳定。
import type { OverviewResp, AgentRow } from "./api";
import { tDynamic } from "./ai/dynamicText";
import { brand } from "./brand";
import { currentLang } from "./i18n";

function esc(s: any): string {
  return cleanReportText(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c] as string));
}

function cleanReportText(value: any): string {
  let text = String(value ?? "—").trim().replace(/^[、，,;；。\s]+/, "");
  const singleQuotedList = text.match(/^\[\s*'([^']+)'\s*\]$/);
  const doubleQuotedList = text.match(/^\[\s*"([^"]+)"\s*\]$/);
  if (singleQuotedList) text = singleQuotedList[1];
  if (doubleQuotedList) text = doubleQuotedList[1];
  return text.trim().replace(/^['"]|['"]$/g, "").replace(/^[、，,;；。\s]+/, "");
}

function triageSeverityText(value: any): string {
  const text = String(value ?? "").trim();
  if (text === "高" || /^high$/i.test(text)) return currentLang === "en" ? "High" : "高危";
  if (text === "中" || /^medium$/i.test(text)) return currentLang === "en" ? "Medium" : "中危";
  if (text === "低" || /^low$/i.test(text)) return currentLang === "en" ? "Low" : "低危";
  if (/^critical$/i.test(text)) return currentLang === "en" ? "Critical" : "严重";
  return tDynamic(text);
}

export function exportReport(ov: OverviewResp, agents: AgentRow[]) {
  const s = ov.summary;
  const ai = ov.ai?.overview?.result || {};
  const triage = ov.ai?.alert_triage?.result || {};
  const comp = ov.ai?.compliance?.result || {};
  const high = (s.alerts.by_severity.high || 0) + (s.alerts.by_severity.critical || 0);
  const online = agents.filter((a) => a.status === "active").length;
  const scores = Object.values(s.compliance).map((c) => c.score || 0).filter(Boolean);
  const avgComp = scores.length ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length) : 0;
  const now = new Date();
  const since = new Date(Date.now() - 7 * 86400_000);
  const en = currentLang === "en";
  const locale = en ? "en-US" : "zh-CN";
  const fmt = (d: Date) => d.toLocaleDateString(locale);
  const L = en ? {
    lang: "en",
    title: `${brand.name} Security Weekly Report`,
    print: "Print / Save as PDF",
    period: "Report period",
    generated: "Generated",
    window: "Data window: last 24 hours",
    posture: "1. Overall Security Posture",
    online: "Online Devices",
    high: "High/Critical Alerts",
    totalAlerts: "Total Alerts (24h)",
    avgCompliance: "Average Compliance",
    risk: "Risk Index",
    actions: "2. Priority Actions",
    clusters: "3. Alert Clustering (AI Noise Reduction)",
    category: "Category",
    meaning: "Meaning",
    count: "Count",
    severity: "Severity",
    compliance: "4. Compliance Check",
    worst: "Lowest compliance endpoint",
    score: "Score",
    device: "Device",
    policy: "Baseline Policy",
    passed: "Passed",
    failed: "Failed",
    hardening: "Hardening advice:",
    none: "N/A",
    noData: "No data",
    footer: `Generated by ${brand.name} · Data source: Wazuh + AI analysis`,
    popupBlocked: "The browser blocked the popup. Please allow popups for this site and retry exporting the report.",
  } : {
    lang: "zh-CN",
    title: `${brand.name} 企业安全周报`,
    print: "打印 / 存为 PDF",
    period: "报告周期",
    generated: "生成时间",
    window: "数据窗口：近 24 小时",
    posture: "一、整体安全态势",
    online: "在线设备",
    high: "高危/严重告警",
    totalAlerts: "告警总量(24h)",
    avgCompliance: "平均合规分",
    risk: "风险指数",
    actions: "二、优先处置建议",
    clusters: "三、告警归并（AI 降噪）",
    category: "类别",
    meaning: "含义",
    count: "数量",
    severity: "严重度",
    compliance: "四、合规体检",
    worst: "合规最差设备",
    score: "评分",
    device: "设备",
    policy: "基线策略",
    passed: "通过",
    failed: "未通过",
    hardening: "加固建议：",
    none: "暂无",
    noData: "暂无数据",
    footer: `本报告由 ${brand.name} 自动生成 · 数据来源 Wazuh + AI 研判`,
    popupBlocked: "浏览器拦截了弹窗，请允许本站点弹窗后重试导出报告。",
  };

  const actions = (ai.top_actions || []).map((a: string) => `<li>${esc(a)}</li>`).join("");
  const clusters = (triage.clusters || [])
    .map((c: any) => `<tr><td>${esc(tDynamic(c.category))}</td><td>${esc(tDynamic(c.meaning))}</td><td style="text-align:center">${esc(c.count)}</td><td style="text-align:center">${esc(triageSeverityText(c.severity))}</td></tr>`)
    .join("");
  const compRows = Object.entries(s.compliance)
    .map(([name, c]) => `<tr><td>${esc(name)}</td><td>${esc(c.policy)}</td><td style="text-align:center">${esc(c.score)}</td><td style="text-align:center">${esc(c.pass)}</td><td style="text-align:center">${esc(c.fail)}</td></tr>`)
    .join("");
  const recs = (comp.recommendations || []).map((r: string) => `<li>${esc(r)}</li>`).join("");

  const html = `<!doctype html><html lang="${L.lang}"><head><meta charset="utf-8">
<title>${L.title} ${fmt(now)}</title>
<style>
  @page { size: A4; margin: 16mm; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system,"PingFang SC","Microsoft YaHei",sans-serif; color: #18181b; margin: 0; }
  h1 { font-size: 24px; margin: 0 0 4px; }
  h2 { font-size: 16px; margin: 26px 0 10px; padding-bottom: 6px; border-bottom: 2px solid #18181b; }
  .muted { color: #71717a; font-size: 13px; }
  .kpis { display: grid; grid-template-columns: repeat(5,1fr); gap: 10px; margin-top: 14px; }
  .kpi { border: 1px solid #e4e4e7; border-radius: 10px; padding: 12px; }
  .kpi .l { font-size: 12px; color: #71717a; }
  .kpi .v { font-size: 24px; font-weight: 800; margin-top: 4px; }
  .danger .v { color: #dc2626; }
  .ok .v { color: #16a34a; }
  .box { border: 1px solid #e4e4e7; border-radius: 10px; padding: 14px; margin-top: 8px; }
  .headline { font-size: 16px; font-weight: 700; margin-bottom: 6px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 8px; }
  th, td { border: 1px solid #e4e4e7; padding: 7px 9px; text-align: left; }
  th { background: #f4f4f5; }
  ul { margin: 6px 0; padding-left: 20px; } li { margin: 4px 0; }
  .pill { display: inline-block; padding: 2px 10px; border-radius: 999px; background: #18181b; color: #fff; font-size: 12px; }
  .foot { margin-top: 30px; color: #a1a1aa; font-size: 11px; text-align: center; }
  @media print { .noprint { display: none; } }
</style></head><body>
  <div class="noprint" style="background:#18181b;padding:10px 14px;text-align:right">
    <button onclick="window.print()" style="padding:8px 18px;font-size:14px;font-weight:700;border:0;border-radius:8px;background:#fff;color:#18181b;cursor:pointer">${L.print}</button>
  </div>
  <div style="padding:8px 4px">
  <h1>${L.title}</h1>
  <div class="muted">${L.period}: ${fmt(since)} ~ ${fmt(now)} ｜ ${L.generated}: ${esc(now.toLocaleString(locale))} ｜ ${L.window}</div>

  <h2>${L.posture}</h2>
  <div class="kpis">
    <div class="kpi"><div class="l">${L.online}</div><div class="v">${online}/${agents.length}</div></div>
    <div class="kpi danger"><div class="l">${L.high}</div><div class="v">${high}</div></div>
    <div class="kpi"><div class="l">${L.totalAlerts}</div><div class="v">${esc(s.alerts.total)}</div></div>
    <div class="kpi ${avgComp >= 60 ? "ok" : ""}"><div class="l">${L.avgCompliance}</div><div class="v">${avgComp}</div></div>
    <div class="kpi"><div class="l">${L.risk}</div><div class="v">${esc(ai.risk_score)}</div></div>
  </div>
  <div class="box">
    <div class="headline">${esc(ai.headline)} <span class="pill">${esc(ai.risk_level)}</span></div>
    <div>${esc(ai.summary)}</div>
  </div>

  <h2>${L.actions}</h2>
  <ul>${actions || `<li>${L.none}</li>`}</ul>

  <h2>${L.clusters}</h2>
  <table><thead><tr><th>${L.category}</th><th>${L.meaning}</th><th>${L.count}</th><th>${L.severity}</th></tr></thead>
  <tbody>${clusters || `<tr><td colspan="4">${L.noData}</td></tr>`}</tbody></table>

  <h2>${L.compliance}</h2>
  <div class="muted">${L.worst}: <b>${esc(comp.worst_endpoint)}</b>（${esc(comp.worst_score)} ${L.score}）</div>
  <table><thead><tr><th>${L.device}</th><th>${L.policy}</th><th>${L.score}</th><th>${L.passed}</th><th>${L.failed}</th></tr></thead>
  <tbody>${compRows || `<tr><td colspan="5">${L.noData}</td></tr>`}</tbody></table>
  ${recs ? `<div style="margin-top:10px"><b>${L.hardening}</b><ul>${recs}</ul></div>` : ""}

  <div class="foot">${L.footer}</div>
  </div>
  <script>setTimeout(function(){ try { window.focus(); } catch(e){} }, 200);</script>
</body></html>`;

  const w = window.open("", "_blank");
  if (!w) {
    alert(L.popupBlocked);
    return;
  }
  w.document.open();
  w.document.write(html);
  w.document.close();
}
